# Generated by Django 6.1 on 2026-09-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('github_url', models.URLField(blank=True, max_length=250)),
                ('linkedin_url', models.URLField(blank=True, max_length=250)),
                ('copyright', models.CharField(blank=True, max_length=200)),
                ('made_with', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
