# Generated by Django 6.1 on 2026-09-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_main_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name_plural': 'Main Details'},
        ),
        migrations.AddField(
            model_name='main',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='main',
            name='title',
            field=models.CharField(blank=True, help_text='This is a text. Not an image.', max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='logo',
            field=models.CharField(blank=True, help_text='This is a text. Not an image.', max_length=50),
        ),
    ]
