# Generated by Django 6.1 on 2026-09-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_main_options_main_description_main_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='footer_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='title',
            field=models.CharField(blank=True, help_text='This is a text. Not an image.', max_length=75),
        ),
    ]
