# Generated by Django 6.1 on 2026-09-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_main_footer_description_alter_main_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='main/'),
        ),
    ]
