# Generated by Django 6.1 on 2026-09-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_main_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='عنوان')),
                ('featured_image', models.ImageField(upload_to='projects/')),
                ('description', models.TextField(blank=True)),
                ('view_projects_link', models.URLField(blank=True)),
                ('view_code_link', models.URLField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='با کاما جدا کنید: HTML, CSS, JS', max_length=150, verbose_name='تگ\u200cها')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
