# Generated by Django 6.1 on 2026-09-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skills_description',
            field=models.TextField(blank=True, default='Building skills in frontend, python and Django'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skills_title',
            field=models.CharField(blank=True, default='I Work With', max_length=100),
        ),
    ]
