# Generated by Django 6.1 on 2026-09-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_skill_skills_description_skill_skills_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skills_description',
            field=models.TextField(blank=True, default='Building skills in'),
        ),
    ]
