# Generated by Django 6.1 on 2026-09-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_skill_skills_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skills_description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skills_title',
        ),
        migrations.AddField(
            model_name='main',
            name='about_label',
            field=models.CharField(blank=True, default='About Me', max_length=100),
        ),
        migrations.AddField(
            model_name='main',
            name='about_text',
            field=models.TextField(blank=True, default='Full-stack developer with frontend expertise and growing backend skills.'),
        ),
        migrations.AddField(
            model_name='main',
            name='about_title',
            field=models.CharField(blank=True, default='A little bit about me', max_length=150),
        ),
        migrations.AddField(
            model_name='main',
            name='journey_title',
            field=models.CharField(blank=True, default='My Journey', max_length=100),
        ),
        migrations.AddField(
            model_name='main',
            name='skills_description',
            field=models.TextField(blank=True, default='Building skills in frontend, Python, and Django.'),
        ),
        migrations.AddField(
            model_name='main',
            name='skills_title',
            field=models.CharField(blank=True, default='I Work With', max_length=100),
        ),
    ]
